globalvar last_words;

last_words = ds_list_create();

ds_list_add(last_words, "I'll be back");
ds_list_add(last_words, "Needs of one outweight the need of many");
ds_list_add(last_words, "Should have dodged left");
ds_list_add(last_words, "Should have dodged right");
ds_list_add(last_words, "Press F to pay respect");
ds_list_add(last_words, "I hate sand");
ds_list_add(last_words, "I can make it");
ds_list_add(last_words, "I am suprisingly good driver");
ds_list_add(last_words, "So that's how to drive a car");
ds_list_add(last_words, "Oh, finally. I see!");
ds_list_add(last_words, "Dammit");
ds_list_add(last_words, "He's dead, Jim");
ds_list_add(last_words, "Shouldn't have the second sandwich");
ds_list_add(last_words, "Resistance is futile");
ds_list_add(last_words, "I will return");
ds_list_add(last_words, "Dodge this!");
ds_list_add(last_words, "I'll be back when the snow falls");
ds_list_add(last_words, "Don't worry, I got this");
ds_list_add(last_words, "Should have used shield");
ds_list_add(last_words, "Wow, that was close");
ds_list_add(last_words, "Would have looked cooler in slow-motion");
ds_list_add(last_words, "For the Alliance");
ds_list_add(last_words, "Did not expect that");
ds_list_add(last_words, "Last words are for fools that haven't said enough");
ds_list_add(last_words, "I bet I will be ressurected next season");
ds_list_add(last_words, "Oops");
ds_list_add(last_words, "Sorry about that");
ds_list_add(last_words, "I'll take you down with me");
ds_list_add(last_words, "You're not gonna get me alive");
ds_list_add(last_words, "You shall not pass");
ds_list_add(last_words, "Got it! Or no?");
ds_list_add(last_words, "Anger the cops, they said. It will be fun, they said");
ds_list_add(last_words, "It's french fries not chips");
